#
# Makefile for the SuperH specific drivers.
#
obj-y	:= intc/

obj-$(CONFIG_HAVE_CLK)		+= clk/
obj-$(CONFIG_MAPLE)		+= maple/
obj-$(CONFIG_MACH_U2EVM)	+= mdmloader/
obj-$(CONFIG_MACH_GARDALTE)	+= mdmloader/
obj-$(CONFIG_MACH_LOGANLTE)	+= mdmloader/
obj-$(CONFIG_MACH_LT02LTE)	+= mdmloader/
obj-$(CONFIG_MACH_U2EVM)	+= dummy-netdev/
obj-$(CONFIG_MACH_GARDALTE)	+= dummy-netdev/
obj-$(CONFIG_MACH_LOGANLTE)   	+= dummy-netdev/
obj-$(CONFIG_MACH_LT02LTE)	+= dummy-netdev/
obj-$(CONFIG_SUPERHYWAY)	+= superhyway/
obj-$(CONFIG_GENERIC_GPIO)	+= pfc.o
# obj-y				+= pm_runtime.o
