#
# Makefile for Richtek I2C micro USB switch drivers.
#


obj-$(CONFIG_RT8969)		+= rt8969.o
obj-$(CONFIG_RT8973)		+= rt8973.o
obj-$(CONFIG_RT9450AC)      += rt9450.o
obj-$(CONFIG_RT9450B)       += rt9450.o
obj-$(CONFIG_RT9451)        += rt9451.o
obj-$(CONFIG_RT9452)        += rt9452.o
obj-$(CONFIG_RT9453)        += rt9453.o
