obj-$(CONFIG_PMIC_INTERFACE)      	+= interface.o
obj-$(CONFIG_PMIC_TPS80032_POW)      	+= pmic-tps80032.o
obj-$(CONFIG_USB_OTG_INTERFACE)      	+= usb_otg_interface.o

EXTRA_CFLAGS += -I $(srctree)/arch/arm/mach-shmobile/include
