obj-$(CONFIG_PMIC_INTERFACE)      	+= interface.o
obj-$(CONFIG_PMIC_TPS80032_POW)      	+= pmic-tps80032.o
obj-$(CONFIG_USB_OTG_INTERFACE)      	+= usb_otg_interface.o
obj-$(CONFIG_PMIC_NCP6914)			+= subpmic_ncp6914.o
EXTRA_CFLAGS += -I $(srctree)/arch/arm/mach-shmobile/include
subdir-ccflags-y += -Werror
