# Makefile for R-Mobile framebuffer device driver
#

obj-$(CONFIG_FB_R_MOBILE_NT35510)      += panel_nt35510.o
obj-$(CONFIG_FB_R_MOBILE_NT35516)      += panel_nt35516.o
obj-$(CONFIG_FB_R_MOBILE_VX5B3D)       += panel_vx5b3d.o

