# Makefile for R-Mobile framebuffer device driver
#

obj-$(CONFIG_FB_R_MOBILE_PANEL_SWITCH) += panel_switch.o

obj-$(CONFIG_FB_R_MOBILE_PANEL_KOTA)   += panel_kota.o
obj-$(CONFIG_FB_R_MOBILE_S6E39A0X02)   += panel_s6e39a0x02.o
obj-$(CONFIG_FB_R_MOBILE_HX8369_B)     += panel_hx8369_b.o
obj-$(CONFIG_FB_R_MOBILE_NT35510_COMMAND_MODE)    += panel_nt35510.o
obj-$(CONFIG_FB_R_MOBILE_NT35510_VIDEO_MODE)      += panel_nt35510.o
obj-$(CONFIG_FB_R_MOBILE_VX5B3D)       += panel_vx5b3d.o

