obj-$(CONFIG_VIBRATOR)	+= vibrator.o

#option 1
#enable below instruction to use PCM2PWM with DC Motor
# ccflags-y := -DVIB_PCM2PWM -DVIB_DCMOTOR

#option 2
#enable below instruction to use PCM2PWM with Linear Motor
# ccflags-y := -DVIB_PCM2PWM

#option 3
#enable below instruction to use TPU with DC Motor
ccflags-y := -DVIB_DCMOTOR

