# Makefile for rtapi driver

obj-$(CONFIG_MISC_R_MOBILE_COMPOSER_APPMEM_SHAREMANGER) += sh_mobile_appmem.o
obj-$(CONFIG_MISC_R_MOBILE_COMPOSER)                  += sh_mobile_composer.o

EXTRA_CFLAGS += -Idrivers/char/composer
