#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_MELFAS)    += melfas_ts.o MMS100S_ISC_Updater_V01.o MMS100S_ISC_Updater_Customize.o
