#
# Makefile for the Cypress touchkey driver
#

obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH) += cypress_touch_key.o

cypress_touch_key-y := \
	cypress-touchkey.o \
	issp_driver_routines.o \
	issp_main.o issp_routines.o

