/*
 * arch/arm/mach-shmobile/include/mach/memory-r8a7373.h
 *
 * Copyright (C) 2012 Renesas Mobile Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

#ifndef __MEMORY_R8A7373_H__
#define __MEMORY_R8A7373_H__

/* Please refer EOSCDP-DES-0009988_AnnexA.xlsx */

#define SDRAM_MODEM_START_ADDR				0x40000000
#define SDRAM_MODEM_END_ADDR				0x43FBFFFF
#define SDRAM_DIAMOND_START_ADDR			0x43FC0000
#define SDRAM_DIAMOND_END_ADDR				0x43FFFFFF

#define SDRAM_STM_TRACE_BUFFER_START_ADDR		0x44000000
#define SDRAM_STM_TRACE_BUFFER_END_ADDR			0x44FFFFFF
#define SDRAM_NON_SECURE_SPINLOCK_START_ADDR		0x45000000
#define SDRAM_NON_SECURE_SPINLOCK_END_ADDR		0x45000FFF
#define SDRAM_SMC_START_ADDR				0x45001000
#define SDRAM_SMC_END_ADDR				0x457FFBFF
#define SDRAM_CRASHLOG_START_ADDR			0x457FFC00
#define SDRAM_MEMLOG_START_ADDRESS			0xE63C0000
#define SDRAM_MEMLOG_END_ADDRESS			0xE63C0FFF
#define SDRAM_CRASHLOG_END_ADDR				0x458FFBFF
#define SDRAM_SOFT_SEMAPHORE_TVRF_START_ADDR		0x458FFC00
#define SDRAM_SOFT_SEMAPHORE_TVRF_END_ADDR		0x458FFC7F
#define SDRAM_SOFT_SEMAPHORE_FREQ_START_ADDR		0x458FFC80
#define SDRAM_SOFT_SEMAPHORE_FREQ_END_ADDR		0x458FFDFF
#define SDRAM_SOFT_SEMAPHORE_E20_START_ADDR		0x458FFE00
#define SDRAM_SOFT_SEMAPHORE_E20_END_ADDR		0x458FFE7F
/* Reserved 458FFE80 - 458FFF7F */
#define SDRAM_NON_VOLATILE_FLAG_AREA_START_ADDR		0x458FFF80
#define SDRAM_NON_VOLATILE_FLAG_AREA_END_ADDR		0x458FFFFF

#define SDRAM_SDTOC_START_ADDR				0x45900000
#define SDRAM_SDTOC_END_ADDR				0x459FDFFF
#define SDRAM_SECURE_SPINLOCK_AND_DATA_START_ADDR	0x459FE000
#define SDRAM_SECURE_SPINLOCK_AND_DATA_END_ADDR		0x459FFFFF

#define SDRAM_REGISTER_DUMP_AREA_START_ADDR		0x45A00000
#define SDRAM_REGISTER_DUMP_AREA_END_ADDR		0x45A07FFF

/* Reserved 45A08000 - 45AFFFFF */

#define SDRAM_FRAME_BUFFER_START_ADDR			0x45B00000
#define SDRAM_FRAME_BUFFER_END_ADDR			0x45EFFFFF

#define SDRAM_MFI_START_ADDR				0x45F00000
#define SDRAM_MFI_END_ADDR				0x45FFFFFF
#define SDRAM_SH_FIRM_START_ADDR			0x46000000
#define SDRAM_SH_FIRM_END_ADDR				0x47BFFFFF
#define SDRAM_ROTATION_BUFFER_START_ADDR		0x47C00000
#define SDRAM_ROTATION_BUFFER_END_ADDR			0x48FFFFFF

#define SDRAM_TUNE_UP_VALUE_START_ADDR			0x48B00000
#define SDRAM_TUNE_UP_VALUE_END_ADDR			0x48EFFFFF

#define SDRAM_VOCODER_START_ADDR			0x4F800000
#define SDRAM_VOCODER_END_ADDR				0x4FFFFFFF

#define SDRAM_KERNEL_START_ADDR				0x49000000
#define SDRAM_KERNEL_END_ADDR				0x7FFFFFFF

#endif /* __MEMORY_R8A7373_H__ */
