obj-$(CONFIG_MCI)	+= mci-core.o
obj-$(CONFIG_MCI_MXS) += mxs.o
obj-$(CONFIG_MCI_S3C) += s3c.o
obj-$(CONFIG_MCI_IMX) += imx.o
obj-$(CONFIG_MCI_IMX_ESDHC) += imx-esdhc.o
obj-$(CONFIG_MCI_OMAP_HSMMC) += omap_hsmmc.o
obj-$(CONFIG_MCI_R_MOBILE_MMCIF) += r_mobile_mmcif.o
obj-$(CONFIG_MCI_R_MOBILE_SDHI) += r_mobile_sdhi.o

