#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_BOARD_VERSION_GARDA)		+= gardalte/
obj-$(CONFIG_BOARD_VERSION_LOGANLTE)	+= loganlte/
obj-$(CONFIG_BOARD_VERSION_AMETHYST)	+= loganlte/

