##########################################################
#
# Makefile for the kernel Sensor device drivers.
#
##############################################################

# Object files in subdirectories

obj-$(CONFIG_SENSOR_SUPPORT)		+= accelerometer/
obj-$(CONFIG_SENSOR_SUPPORT)		+= gyroscope/
obj-$(CONFIG_SENSOR_SUPPORT)		+= proximity/

