#
# Makefile for the Renesas Dummy netdev.
#

obj-$(CONFIG_MACH_U2EVM)      += renesas_dummy_netdev.o
obj-$(CONFIG_MACH_GARDALTE)      += renesas_dummy_netdev.o
obj-$(CONFIG_MACH_LOGANLTE)      += renesas_dummy_netdev.o
